/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/auth/register': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Register
     * @description Register a new user account.
     */
    post: operations['register_api_v1_auth_register_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Login
     * @description Authenticate and log in.
     */
    post: operations['login_api_v1_auth_login_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Refresh Token
     * @description Refresh the access token using a refresh token from cookie.
     */
    post: operations['refresh_token_api_v1_auth_refresh_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Logout
     * @description Log out by clearing auth cookies.
     */
    post: operations['logout_api_v1_auth_logout_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Me
     * @description Get the currently authenticated user's profile.
     */
    get: operations['get_me_api_v1_auth_me_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/servers/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Api Health
     * @description Health check endpoint for the API service.
     */
    get: operations['api_health_api_v1_servers_health_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/servers': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Servers
     * @description List all MCP servers for the current user.
     */
    get: operations['list_servers_api_v1_servers_get'];
    put?: never;
    /**
     * Create Server
     * @description Create a new MCP server.
     */
    post: operations['create_server_api_v1_servers_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/servers/{server_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Server
     * @description Get a specific MCP server by ID.
     */
    get: operations['get_server_api_v1_servers__server_id__get'];
    put?: never;
    post?: never;
    /**
     * Delete Server
     * @description Delete an MCP server.
     */
    delete: operations['delete_server_api_v1_servers__server_id__delete'];
    options?: never;
    head?: never;
    /**
     * Update Server
     * @description Update an MCP server.
     */
    patch: operations['update_server_api_v1_servers__server_id__patch'];
    trace?: never;
  };
  '/mcp/v1/{slug}/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Mcp Server Health
     * @description Health check for a specific MCP server.
     */
    get: operations['mcp_server_health_mcp_v1__slug__health_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/mcp/v1/{slug}/sse': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Mcp Sse Endpoint
     * @description SSE transport endpoint for MCP protocol.
     *
     *     Establishes an SSE connection and handles the MCP protocol lifecycle.
     */
    get: operations['mcp_sse_endpoint_mcp_v1__slug__sse_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/mcp/v1/{slug}/message': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Mcp Message Endpoint
     * @description Message endpoint for SSE transport.
     *
     *     Receives JSON-RPC messages sent via POST during an SSE session.
     */
    post: operations['mcp_message_endpoint_mcp_v1__slug__message_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/mcp/v1/{slug}/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Mcp Http Endpoint
     * @description StreamableHTTP transport endpoint for MCP protocol.
     *
     *     For Phase 1, returns a single JSON-RPC response.
     *     # TODO(phase-2): Implement streaming response for StreamableHTTP.
     */
    post: operations['mcp_http_endpoint_mcp_v1__slug___post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health Check
     * @description Root health check endpoint.
     *
     *     Checks database and Redis connectivity (best-effort).
     *     Returns ok even if dependencies are down — just marks them.
     */
    get: operations['health_check_health_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * APIHealthResponse
     * @description Response from the API v1 health check.
     */
    APIHealthResponse: {
      /**
       * Status
       * @default ok
       */
      status: string;
      /**
       * Version
       * @default 0.1.0
       */
      version: string;
      /**
       * Environment
       * @default development
       */
      environment: string;
    };
    /**
     * AuthResponse
     * @description Response body after successful authentication.
     */
    AuthResponse: {
      /** Id */
      id: string;
      /** Email */
      email: string;
      /** Display Name */
      display_name?: string | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /**
     * HealthResponse
     * @description Response from the root health check endpoint.
     */
    HealthResponse: {
      /**
       * Status
       * @default ok
       */
      status: string;
      /**
       * Version
       * @default 0.1.0
       */
      version: string;
      /**
       * Db
       * @default ok
       */
      db: string;
      /**
       * Redis
       * @default ok
       */
      redis: string;
    };
    /**
     * LoginRequest
     * @description Request body for user login.
     */
    LoginRequest: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Password */
      password: string;
    };
    /**
     * MCPServerCreate
     * @description Request body for creating a new MCP server.
     */
    MCPServerCreate: {
      /** Name */
      name: string;
      /**
       * Slug
       * @description Lowercase alphanumeric with hyphens, 3-50 chars
       */
      slug: string;
      /** Description */
      description?: string | null;
      /** Base Url */
      base_url: string;
      /** Spec Url */
      spec_url?: string | null;
      /**
       * Auth Scheme
       * @default none
       */
      auth_scheme: string;
      /** Auth Header Name */
      auth_header_name?: string | null;
      /** Tools Config */
      tools_config?: Record<string, never>;
      /**
       * Transport Mode
       * @default sse
       */
      transport_mode: string;
    };
    /**
     * MCPServerResponse
     * @description Public MCP server response.
     */
    MCPServerResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
      /** Slug */
      slug: string;
      /** Name */
      name: string;
      /** Description */
      description?: string | null;
      /**
       * Status
       * @default building
       */
      status: string;
      /** Spec Url */
      spec_url?: string | null;
      /** Base Url */
      base_url: string;
      /**
       * Auth Scheme
       * @default none
       */
      auth_scheme: string;
      /**
       * Transport Mode
       * @default sse
       */
      transport_mode: string;
      /** Tools Config */
      tools_config: Record<string, never>;
      /**
       * Total Calls
       * @default 0
       */
      total_calls: number;
      /**
       * Monthly Calls
       * @default 0
       */
      monthly_calls: number;
      /** Last Call At */
      last_call_at?: string | null;
      /**
       * Version
       * @default 1
       */
      version: number;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Updated At */
      updated_at?: string | null;
    };
    /**
     * MCPServerUpdate
     * @description Request body for updating an MCP server.
     */
    MCPServerUpdate: {
      /** Name */
      name?: string | null;
      /** Description */
      description?: string | null;
      /** Base Url */
      base_url?: string | null;
      /** Auth Scheme */
      auth_scheme?: string | null;
      /** Auth Header Name */
      auth_header_name?: string | null;
      /** Tools Config */
      tools_config?: Record<string, never> | null;
      /** Transport Mode */
      transport_mode?: string | null;
      /** Status */
      status?: string | null;
    };
    /**
     * RegisterRequest
     * @description Request body for user registration.
     */
    RegisterRequest: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Password */
      password: string;
      /** Display Name */
      display_name?: string | null;
    };
    /**
     * UserResponse
     * @description Public user profile response.
     */
    UserResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Email */
      email: string;
      /** Display Name */
      display_name?: string | null;
      /** Avatar Url */
      avatar_url?: string | null;
      /**
       * Plan
       * @default free
       */
      plan: string;
      /**
       * Ai Enhancement Credits
       * @default 3
       */
      ai_enhancement_credits: number;
      /**
       * Email Verified
       * @default false
       */
      email_verified: boolean;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Updated At */
      updated_at?: string | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  register_api_v1_auth_register_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RegisterRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  login_api_v1_auth_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  refresh_token_api_v1_auth_refresh_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        refresh_token?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  logout_api_v1_auth_logout_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: string;
          };
        };
      };
    };
  };
  get_me_api_v1_auth_me_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: {
        access_token?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  api_health_api_v1_servers_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['APIHealthResponse'];
        };
      };
    };
  };
  list_servers_api_v1_servers_get: {
    parameters: {
      query?: {
        skip?: number;
        limit?: number;
      };
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: {
        access_token?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MCPServerResponse'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_server_api_v1_servers_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: {
        access_token?: string | null;
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['MCPServerCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MCPServerResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_server_api_v1_servers__server_id__get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        server_id: string;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MCPServerResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_server_api_v1_servers__server_id__delete: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        server_id: string;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_server_api_v1_servers__server_id__patch: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        server_id: string;
      };
      cookie?: {
        access_token?: string | null;
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['MCPServerUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MCPServerResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  mcp_server_health_mcp_v1__slug__health_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: string;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  mcp_sse_endpoint_mcp_v1__slug__sse_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  mcp_message_endpoint_mcp_v1__slug__message_post: {
    parameters: {
      query?: {
        session_id?: string | null;
      };
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  mcp_http_endpoint_mcp_v1__slug___post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  health_check_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthResponse'];
        };
      };
    };
  };
}
