// This file is auto-generated by @hey-api/openapi-ts

/**
 * POST /api/v1/servers/{id}/tools/enhance body.
 */
export type AIEnhancementRequest = {
    /**
     * If None, enhances all tools. Otherwise, only the named ones.
     */
    tool_names?: (Array<(string)> | null);
    /**
     * If True, re-run even on tools that were already enhanced.
     */
    force?: boolean;
};

/**
 * Response returned immediately after submitting an enhancement job.
 */
export type AIEnhancementResponse = {
    /**
     * Celery task ID for the enhancement job
     */
    job_id: string;
    /**
     * Estimated cost in cents for the full enhancement run
     */
    estimated_cost_cents: number;
    /**
     * Estimated duration in seconds for the full run
     */
    estimated_duration_seconds: number;
    /**
     * AI enhancement credits remaining. None = unlimited (Pro tier).
     */
    remaining_credits?: (number | null);
};

/**
 * Response from the API v1 health check.
 */
export type APIHealthResponse = {
    status?: string;
    version?: string;
    environment?: string;
};

/**
 * Response body after successful authentication.
 */
export type AuthResponse = {
    id: string;
    email: string;
    display_name?: (string | null);
};

export type Body_upload_spec_api_v1_specs_upload_post = {
    file: (Blob | File);
};

/**
 * GET /api/v1/servers/{id}/connect — connection details for the gateway.
 *
 * Returned when a user views the "Connect" panel for their deployed MCP
 * server.  Includes copy-ready config snippets for Claude Desktop and
 * Cursor.
 */
export type ConnectPanelResponse = {
    server_slug: string;
    gateway_url: string;
    transport_modes?: Array<('sse' | 'streamable_http' | 'both')>;
    claude_desktop_config?: {
        [key: string]: unknown;
    };
    cursor_config?: {
        [key: string]: unknown;
    };
    test_connection_endpoint: string;
};

/**
 * Request body for POST /api/v1/servers/{id}/credentials.
 */
export type CredentialCreateRequest = {
    env_var_name: string;
    value: string;
    auth_scheme?: 'bearer' | 'api_key' | 'basic' | 'oauth2' | 'header';
    auth_header_name?: (string | null);
};

export type auth_scheme = 'bearer' | 'api_key' | 'basic' | 'oauth2' | 'header';

/**
 * Response wrapper for listing all credentials on a server.
 */
export type CredentialListResponse = {
    server_id: string;
    credentials: Array<CredentialResponse>;
    total: number;
};

/**
 * Response when listing credentials. NEVER returns the value.
 */
export type CredentialResponse = {
    id: string;
    env_var_name: string;
    auth_scheme: string;
    auth_header_name?: (string | null);
    encryption_key_id: (string | null);
    rotated_at: (string | null);
    last_used_at: (string | null);
    created_at: string;
    updated_at: (string | null);
};

/**
 * Request body for POST /api/v1/servers/{id}/credentials/test.
 */
export type CredentialTestRequest = {
    env_var_name: string;
    test_value: string;
};

/**
 * Response for a credential test request.
 *
 * Note: The F1 spec names this field ``response_time_ms``; we use ``latency_ms``
 * for consistency with pre-existing code in the dashboard and analytics pipeline.
 */
export type CredentialTestResponse = {
    success: boolean;
    status_code: (number | null);
    latency_ms: (number | null);
    error?: (string | null);
};

/**
 * Response from the root health check endpoint.
 */
export type HealthResponse = {
    status?: string;
    version?: string;
    db?: string;
    redis?: string;
    worker?: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * Request body for user login.
 */
export type LoginRequest = {
    email: string;
    password: string;
};

/**
 * Request body for creating a new MCP server.
 */
export type MCPServerCreate = {
    name: string;
    /**
     * Lowercase alphanumeric with hyphens, 3-50 chars
     */
    slug: string;
    description?: (string | null);
    base_url: string;
    spec_url?: (string | null);
    auth_scheme?: string;
    auth_header_name?: (string | null);
    tools_config?: {
        [key: string]: unknown;
    };
    transport_mode?: string;
};

/**
 * Public MCP server response.
 */
export type MCPServerResponse = {
    id: string;
    user_id: string;
    slug: string;
    name: string;
    description?: (string | null);
    status?: string;
    spec_url?: (string | null);
    base_url: string;
    auth_scheme?: string;
    transport_mode?: string;
    tools_config: {
        [key: string]: unknown;
    };
    total_calls?: number;
    monthly_calls?: number;
    last_call_at?: (string | null);
    version?: number;
    created_at: string;
    updated_at?: (string | null);
};

/**
 * Request body for updating an MCP server.
 */
export type MCPServerUpdate = {
    name?: (string | null);
    description?: (string | null);
    base_url?: (string | null);
    auth_scheme?: (string | null);
    auth_header_name?: (string | null);
    tools_config?: ({
    [key: string]: unknown;
} | null);
    transport_mode?: (string | null);
    status?: (string | null);
};

/**
 * Response from POST /api/v1/servers/{id}/pause and /resume.
 */
export type PauseResponse = {
    server_id: string;
    status: 'paused' | 'active';
    paused_at?: (string | null);
    /**
     * Estimated time for the status change to propagate through the gateway
     */
    estimated_propagation_seconds?: number;
};

export type status = 'paused' | 'active';

/**
 * Request body for user registration.
 */
export type RegisterRequest = {
    email: string;
    password: string;
    display_name?: (string | null);
};

/**
 * Request body for POST /specs/fetch.
 */
export type SpecFetchRequest = {
    url: string;
    headers?: ({
    [key: string]: (string);
} | null);
};

/**
 * Response for GET /specs/{spec_id} — spec metadata.
 */
export type SpecSourceResponse = {
    id: string;
    user_id: string;
    source_type: string;
    source_url?: (string | null);
    r2_key?: (string | null);
    title?: (string | null);
    version?: (string | null);
    openapi_version?: (string | null);
    endpoint_count?: (number | null);
    spec_size_bytes?: (number | null);
    fetch_status?: string;
    fetch_error?: (string | null);
    created_at: string;
    updated_at?: (string | null);
};

/**
 * Response for GET /api/v1/specs/{spec_id}/tools.
 */
export type SpecToolListResponse = {
    spec_id: string;
    tools: Array<ToolDefinition>;
};

/**
 * Response for a successful spec upload/fetch.
 */
export type SpecUploadResponse = {
    spec_id: string;
    title: (string | null);
    version: (string | null);
    openapi_version: (string | null);
    endpoint_count: number;
    spec_size_bytes: number;
    tools?: Array<ToolDefinition>;
};

/**
 * POST /api/v1/servers/{id}/test-connection — result of a dry-run call.
 *
 * Unlike the credential test (which tests auth), this tests the full
 * MCP tool invocation pipeline from gateway through upstream.
 */
export type TestConnectionResponse = {
    success: boolean;
    response_time_ms: number;
    tools_count?: (number | null);
    error?: (string | null);
};

/**
 * POST /api/v1/servers/{id}/tools/accept — accept/reject AI suggestions.
 */
export type ToolAcceptRequest = {
    /**
     * Tool names whose AI enhancements to accept
     */
    accepted_tools: Array<(string)>;
    /**
     * Tool names whose AI enhancements to reject (keep original)
     */
    rejected_tools?: Array<(string)>;
    /**
     * Manual overrides keyed by tool name, value is a dict of fields to set
     */
    custom_edits?: {
        [key: string]: {
            [key: string]: unknown;
        };
    };
};

export type ToolDefinition = {
    [key: string]: unknown;
};

/**
 * Response for GET /api/v1/servers/{id}/tools.
 */
export type ToolListResponse = {
    server_id: string;
    tool_count: number;
    tools: Array<{
        [key: string]: unknown;
    }>;
};

/**
 * Request body for POST /specs/{spec_id}/select-tools.
 */
export type ToolSelectionRequest = {
    /**
     * Lowercase alphanumeric with hyphens, 3-50 chars
     */
    slug: string;
    name: string;
    base_url: string;
    description?: (string | null);
    auth_scheme?: string;
    auth_header_name?: (string | null);
    /**
     * Names of tools the user selected to include
     */
    selected_tool_names: Array<(string)>;
    customizations?: ({
    [key: string]: {
        [key: string]: unknown;
    };
} | null);
    transport_mode?: string;
};

/**
 * Request body for PATCH /api/v1/servers/{id}/tools/{tool_name}.
 *
 * All fields are optional. Only non-None values are applied.
 */
export type ToolUpdateRequest = {
    description?: (string | null);
    enabled?: (boolean | null);
    name?: (string | null);
};

/**
 * Public user profile response.
 */
export type UserResponse = {
    id: string;
    email: string;
    display_name?: (string | null);
    avatar_url?: (string | null);
    plan?: string;
    ai_enhancement_credits?: number;
    email_verified?: boolean;
    created_at: string;
    updated_at?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type AnalyticsOverviewApiV1ServersServerIdAnalyticsGetData = {
    serverId: string;
};

export type ToolBreakdownApiV1ServersServerIdAnalyticsToolsGetData = {
    serverId: string;
};

export type ErrorLogApiV1ServersServerIdAnalyticsErrorsGetData = {
    serverId: string;
};

export type ClientBreakdownApiV1ServersServerIdAnalyticsClientsGetData = {
    serverId: string;
};

export type TimeseriesApiV1ServersServerIdAnalyticsTimeseriesGetData = {
    serverId: string;
};

export type ExportCsvApiV1ServersServerIdAnalyticsExportCsvGetData = {
    serverId: string;
};

export type RevokeApiKeyApiV1ApiKeysKeyIdDeleteData = {
    keyId: string;
};

export type RegisterApiV1AuthRegisterPostData = {
    requestBody: RegisterRequest;
};

export type RegisterApiV1AuthRegisterPostResponse = (AuthResponse);

export type LoginApiV1AuthLoginPostData = {
    requestBody: LoginRequest;
};

export type LoginApiV1AuthLoginPostResponse = (AuthResponse);

export type RefreshTokenApiV1AuthRefreshPostData = {
    refreshToken?: (string | null);
};

export type RefreshTokenApiV1AuthRefreshPostResponse = (AuthResponse);

export type LogoutApiV1AuthLogoutPostData = {
    accessToken?: (string | null);
    authorization?: (string | null);
};

export type LogoutApiV1AuthLogoutPostResponse = ({
    [key: string]: (string);
});

export type GetMeApiV1AuthMeGetData = {
    accessToken?: (string | null);
    authorization?: (string | null);
};

export type GetMeApiV1AuthMeGetResponse = (UserResponse);

export type StartBuildApiV1ServersServerIdBuildPostData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    serverId: string;
};

export type StartBuildApiV1ServersServerIdBuildPostResponse = (AIEnhancementResponse);

export type BuildStatusSseApiV1ServersServerIdBuildStatusGetData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    serverId: string;
};

export type BuildStatusSseApiV1ServersServerIdBuildStatusGetResponse = (unknown);

export type AcceptAiEnhancementsApiV1ServersServerIdToolsAcceptPostData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    requestBody: ToolAcceptRequest;
    serverId: string;
};

export type AcceptAiEnhancementsApiV1ServersServerIdToolsAcceptPostResponse = ({
    [key: string]: unknown;
});

export type DeployServerApiV1ServersServerIdDeployPostData = {
    serverId: string;
};

export type ListCredentialsApiV1ServersServerIdCredentialsGetData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    serverId: string;
};

export type ListCredentialsApiV1ServersServerIdCredentialsGetResponse = (CredentialListResponse);

export type AddCredentialApiV1ServersServerIdCredentialsPostData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    requestBody: CredentialCreateRequest;
    serverId: string;
};

export type AddCredentialApiV1ServersServerIdCredentialsPostResponse = (CredentialResponse);

export type TestCredentialApiV1ServersServerIdCredentialsTestPostData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    requestBody: CredentialTestRequest;
    serverId: string;
};

export type TestCredentialApiV1ServersServerIdCredentialsTestPostResponse = (CredentialTestResponse);

export type DeleteCredentialApiV1ServersServerIdCredentialsEnvVarNameDeleteData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    envVarName: string;
    serverId: string;
};

export type DeleteCredentialApiV1ServersServerIdCredentialsEnvVarNameDeleteResponse = (void);

export type McpServerHealthMcpV1SlugHealthGetData = {
    slug: string;
};

export type McpServerHealthMcpV1SlugHealthGetResponse = ({
    [key: string]: (string);
});

export type McpSseEndpointMcpV1SlugSseGetData = {
    slug: string;
};

export type McpSseEndpointMcpV1SlugSseGetResponse = (unknown);

export type McpMessageEndpointMcpV1SlugMessagePostData = {
    sessionId?: (string | null);
    slug: string;
};

export type McpMessageEndpointMcpV1SlugMessagePostResponse = (unknown);

export type McpHttpGetEndpointMcpV1SlugGetData = {
    slug: string;
};

export type McpHttpGetEndpointMcpV1SlugGetResponse = (unknown);

export type McpHttpEndpointMcpV1SlugPostData = {
    slug: string;
};

export type McpHttpEndpointMcpV1SlugPostResponse = (unknown);

export type HealthCheckHealthGetResponse = (HealthResponse);

export type ConnectPanelApiV1ServersServerIdConnectGetData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    serverId: string;
};

export type ConnectPanelApiV1ServersServerIdConnectGetResponse = (ConnectPanelResponse);

export type TestConnectionApiV1ServersServerIdConnectTestPostData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    serverId: string;
};

export type TestConnectionApiV1ServersServerIdConnectTestPostResponse = (TestConnectionResponse);

export type PauseServerApiV1ServersServerIdPausePostData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    serverId: string;
};

export type PauseServerApiV1ServersServerIdPausePostResponse = (PauseResponse);

export type ResumeServerApiV1ServersServerIdResumePostData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    serverId: string;
};

export type ResumeServerApiV1ServersServerIdResumePostResponse = (PauseResponse);

export type RollbackServerApiV1ServersServerIdRollbackPostData = {
    serverId: string;
};

export type ListVersionsApiV1ServersServerIdVersionsGetData = {
    serverId: string;
};

export type TriggerScanApiV1ServersServerIdSecurityScanPostData = {
    serverId: string;
};

export type GetLatestScanApiV1ServersServerIdSecurityLatestGetData = {
    serverId: string;
};

export type ListScansApiV1ServersServerIdSecurityScansGetData = {
    serverId: string;
};

export type AcknowledgeFindingApiV1ServersServerIdSecurityFindingIdAcknowledgePostData = {
    findingId: string;
    serverId: string;
};

export type ExportReportApiV1ServersServerIdSecurityReportJsonGetData = {
    serverId: string;
};

export type ListAcknowledgmentsApiV1ServersServerIdSecurityAcknowledgmentsGetData = {
    serverId: string;
};

export type ApiHealthApiV1ServersHealthGetResponse = (APIHealthResponse);

export type ListServersApiV1ServersGetData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    limit?: number;
    skip?: number;
};

export type ListServersApiV1ServersGetResponse = (Array<MCPServerResponse>);

export type CreateServerApiV1ServersPostData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    requestBody: MCPServerCreate;
};

export type CreateServerApiV1ServersPostResponse = (MCPServerResponse);

export type GetServerApiV1ServersServerIdGetData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    serverId: string;
};

export type GetServerApiV1ServersServerIdGetResponse = (MCPServerResponse);

export type UpdateServerApiV1ServersServerIdPatchData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    requestBody: MCPServerUpdate;
    serverId: string;
};

export type UpdateServerApiV1ServersServerIdPatchResponse = (MCPServerResponse);

export type DeleteServerApiV1ServersServerIdDeleteData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    serverId: string;
};

export type DeleteServerApiV1ServersServerIdDeleteResponse = (void);

export type FetchSpecApiV1SpecsFetchPostData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    requestBody: SpecFetchRequest;
};

export type FetchSpecApiV1SpecsFetchPostResponse = (SpecUploadResponse);

export type UploadSpecApiV1SpecsUploadPostData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    formData: Body_upload_spec_api_v1_specs_upload_post;
};

export type UploadSpecApiV1SpecsUploadPostResponse = (SpecUploadResponse);

export type GetSpecToolsApiV1SpecsSpecIdToolsGetData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    specId: string;
};

export type GetSpecToolsApiV1SpecsSpecIdToolsGetResponse = (SpecToolListResponse);

export type SelectToolsApiV1SpecsSpecIdSelectToolsPostData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    requestBody: ToolSelectionRequest;
    specId: string;
};

export type SelectToolsApiV1SpecsSpecIdSelectToolsPostResponse = (MCPServerResponse);

export type GetSpecApiV1SpecsSpecIdGetData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    specId: string;
};

export type GetSpecApiV1SpecsSpecIdGetResponse = (SpecSourceResponse);

export type DeleteSpecApiV1SpecsSpecIdDeleteData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    specId: string;
};

export type DeleteSpecApiV1SpecsSpecIdDeleteResponse = (void);

export type UpdateMemberApiV1TeamMembersUserIdPatchData = {
    userId: string;
};

export type RemoveMemberApiV1TeamMembersUserIdDeleteData = {
    userId: string;
};

export type ListToolsApiV1ServersServerIdToolsGetData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    serverId: string;
};

export type ListToolsApiV1ServersServerIdToolsGetResponse = (ToolListResponse);

export type UpdateToolApiV1ServersServerIdToolsToolNamePatchData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    requestBody: ToolUpdateRequest;
    serverId: string;
    toolName: string;
};

export type UpdateToolApiV1ServersServerIdToolsToolNamePatchResponse = ({
    [key: string]: unknown;
});

export type EnhanceToolsApiV1ServersServerIdToolsEnhancePostData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    requestBody: AIEnhancementRequest;
    serverId: string;
};

export type EnhanceToolsApiV1ServersServerIdToolsEnhancePostResponse = (AIEnhancementResponse);