// This file is auto-generated by @hey-api/openapi-ts

/**
 * POST /api/v1/servers/{id}/security/{finding_id}/acknowledge.
 */
export type AcknowledgeRequest = {
    note?: (string | null);
};

/**
 * Response for an acknowledge request.
 */
export type AcknowledgeResponse = {
    server_id: string;
    finding_id: string;
    acknowledged_at: string;
};

/**
 * POST /api/v1/servers/{id}/tools/enhance body.
 */
export type AIEnhancementRequest = {
    /**
     * If None, enhances all tools. Otherwise, only the named ones.
     */
    tool_names?: (Array<(string)> | null);
    /**
     * If True, re-run even on tools that were already enhanced.
     */
    force?: boolean;
};

/**
 * Response returned immediately after submitting an enhancement job.
 */
export type AIEnhancementResponse = {
    /**
     * Celery task ID for the enhancement job
     */
    job_id: string;
    /**
     * Estimated cost in cents for the full enhancement run
     */
    estimated_cost_cents: number;
    /**
     * Estimated duration in seconds for the full run
     */
    estimated_duration_seconds: number;
    /**
     * AI enhancement credits remaining. None = unlimited (Pro tier).
     */
    remaining_credits?: (number | null);
};

/**
 * Response from the API v1 health check.
 */
export type APIHealthResponse = {
    status?: string;
    version?: string;
    environment?: string;
};

/**
 * Response for POST /api/v1/api-keys — includes the plaintext ONCE.
 *
 * The plaintext is shown in the UI one time and never again. After
 * creation, only `ApiKeyResponse` (no `plaintext_key`) is returned.
 */
export type ApiKeyCreatedResponse = {
    id: string;
    name: string;
    key_prefix: string;
    scopes: Array<(string)>;
    last_used_at: (string | null);
    expires_at: (string | null);
    revoked_at: (string | null);
    created_at: string;
    /**
     * Shown ONCE at creation. Store securely.
     */
    plaintext_key: string;
};

/**
 * POST /api/v1/api-keys — create a new API key.
 */
export type ApiKeyCreateRequest = {
    name: string;
    /**
     * Permission scopes; see PRD § 13 for the full list.
     */
    scopes?: Array<(string)>;
    expires_in_days?: (number | null);
};

/**
 * Response for GET /api/v1/api-keys — list of keys.
 */
export type ApiKeyListResponse = {
    items: Array<ApiKeyResponse>;
    total: number;
};

/**
 * Response for listing API keys. NEVER returns the plaintext.
 */
export type ApiKeyResponse = {
    id: string;
    name: string;
    key_prefix: string;
    scopes: Array<(string)>;
    last_used_at: (string | null);
    expires_at: (string | null);
    revoked_at: (string | null);
    created_at: string;
};

/**
 * A single audit log entry.
 */
export type AuditLogResponse = {
    id: string;
    user_id?: (string | null);
    user_email?: (string | null);
    action: string;
    resource_type?: (string | null);
    resource_id?: (string | null);
    metadata?: ({
    [key: string]: unknown;
} | null);
    ip_address?: (string | null);
    user_agent?: (string | null);
    created_at: string;
};

/**
 * Response body after successful authentication.
 */
export type AuthResponse = {
    id: string;
    email: string;
    display_name?: (string | null);
};

export type Body_upload_spec_api_v1_specs_upload_post = {
    file: (Blob | File);
};

/**
 * Response for a successful checkout session creation.
 */
export type CheckoutResponse = {
    checkout_url: string;
    session_id: string;
};

/**
 * GET /api/v1/servers/{id}/connect — connection details for the gateway.
 *
 * Returned when a user views the "Connect" panel for their deployed MCP
 * server.  Includes copy-ready config snippets for Claude Desktop and
 * Cursor.
 */
export type ConnectPanelResponse = {
    server_slug: string;
    gateway_url: string;
    transport_modes?: Array<('sse' | 'streamable_http' | 'both')>;
    claude_desktop_config?: {
        [key: string]: unknown;
    };
    cursor_config?: {
        [key: string]: unknown;
    };
    test_connection_endpoint: string;
};

/**
 * Request body for POST /api/v1/servers/{id}/credentials.
 */
export type CredentialCreateRequest = {
    env_var_name: string;
    value: string;
    auth_scheme?: 'bearer' | 'api_key' | 'basic' | 'oauth2' | 'header';
    auth_header_name?: (string | null);
};

export type auth_scheme = 'bearer' | 'api_key' | 'basic' | 'oauth2' | 'header';

/**
 * Response wrapper for listing all credentials on a server.
 */
export type CredentialListResponse = {
    server_id: string;
    credentials: Array<CredentialResponse>;
    total: number;
};

/**
 * Response when listing credentials. NEVER returns the value.
 */
export type CredentialResponse = {
    id: string;
    env_var_name: string;
    auth_scheme: string;
    auth_header_name?: (string | null);
    encryption_key_id: (string | null);
    rotated_at: (string | null);
    last_used_at: (string | null);
    created_at: string;
    updated_at: (string | null);
};

/**
 * Request body for POST /api/v1/servers/{id}/credentials/test.
 */
export type CredentialTestRequest = {
    env_var_name: string;
    test_value: string;
};

/**
 * Response for a credential test request.
 *
 * Note: The F1 spec names this field ``response_time_ms``; we use ``latency_ms``
 * for consistency with pre-existing code in the dashboard and analytics pipeline.
 */
export type CredentialTestResponse = {
    success: boolean;
    status_code: (number | null);
    latency_ms: (number | null);
    error?: (string | null);
};

/**
 * Request body for POST /servers/{id}/duplicate.
 */
export type DuplicateServerRequest = {
    new_name: string;
    /**
     * Kebab-case slug (3-50 chars). Auto-generated from name if omitted.
     */
    new_slug?: (string | null);
};

/**
 * A single security finding from the scanner.
 */
export type Finding = {
    /**
     * Stable finding ID, e.g., 'SSRF_URL_PARAM'
     */
    id: string;
    severity: 'critical' | 'high' | 'medium' | 'info';
    title: string;
    description: string;
    affected_tools?: Array<(string)>;
    remediation: string;
    /**
     * URLs to OWASP, CWE, etc.
     */
    references?: Array<(string)>;
};

export type severity = 'critical' | 'high' | 'medium' | 'info';

/**
 * Request body for initiating a password reset.
 */
export type ForgotPasswordRequest = {
    email: string;
};

/**
 * Response from the root health check endpoint.
 */
export type HealthResponse = {
    status?: string;
    version?: string;
    db?: string;
    redis?: string;
    worker?: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * A single invoice.
 */
export type InvoiceResponse = {
    id: string;
    amount_cents: number;
    currency: string;
    status: string;
    invoice_pdf_url?: (string | null);
    hosted_invoice_url?: (string | null);
    created_at: string;
};

/**
 * Paginated list of invoices.
 */
export type InvoicesListResponse = {
    items: Array<InvoiceResponse>;
    total: number;
    skip?: number;
    limit?: number;
};

/**
 * Request body for user login.
 */
export type LoginRequest = {
    email: string;
    password: string;
};

/**
 * Request body for creating a new MCP server.
 */
export type MCPServerCreate = {
    name: string;
    /**
     * Lowercase alphanumeric with hyphens, 3-50 chars
     */
    slug: string;
    description?: (string | null);
    base_url: string;
    spec_url?: (string | null);
    auth_scheme?: string;
    auth_header_name?: (string | null);
    tools_config?: {
        [key: string]: unknown;
    };
    transport_mode?: string;
};

/**
 * Public MCP server response.
 */
export type MCPServerResponse = {
    id: string;
    user_id: string;
    slug: string;
    name: string;
    description?: (string | null);
    status?: string;
    spec_url?: (string | null);
    base_url: string;
    auth_scheme?: string;
    transport_mode?: string;
    tools_config: {
        [key: string]: unknown;
    };
    total_calls?: number;
    monthly_calls?: number;
    last_call_at?: (string | null);
    version?: number;
    created_at: string;
    updated_at?: (string | null);
};

/**
 * Request body for updating an MCP server.
 */
export type MCPServerUpdate = {
    name?: (string | null);
    description?: (string | null);
    base_url?: (string | null);
    auth_scheme?: (string | null);
    auth_header_name?: (string | null);
    tools_config?: ({
    [key: string]: unknown;
} | null);
    transport_mode?: (string | null);
    status?: (string | null);
};

/**
 * Generic message response.
 */
export type MessageResponse = {
    message: string;
    detail?: (string | null);
};

/**
 * Paginated audit log response.
 */
export type PaginatedAuditLogResponse = {
    items: Array<AuditLogResponse>;
    total: number;
    skip: number;
    limit: number;
};

/**
 * Response from POST /api/v1/servers/{id}/pause and /resume.
 */
export type PauseResponse = {
    server_id: string;
    status: 'paused' | 'active';
    paused_at?: (string | null);
    /**
     * Estimated time for the status change to propagate through the gateway
     */
    estimated_propagation_seconds?: number;
};

export type status = 'paused' | 'active';

/**
 * A single plan as returned by GET /api/v1/billing/plans.
 */
export type PlanInfo = {
    id: string;
    name: string;
    price_cents: number;
    currency?: string;
    period?: string;
    features: Array<(string)>;
    popular?: boolean;
    min_seats?: (number | null);
};

/**
 * Response for GET /api/v1/billing/plans.
 */
export type PlansResponse = {
    plans: Array<PlanInfo>;
};

/**
 * POST /api/v1/billing/portal — get a Stripe customer portal link.
 */
export type PortalRequest = {
    return_url?: (string | null);
};

/**
 * Response for a successful portal session creation.
 */
export type PortalResponse = {
    portal_url: string;
};

/**
 * Request body for user registration.
 */
export type RegisterRequest = {
    email: string;
    password: string;
    display_name?: (string | null);
};

/**
 * Request body for completing a password reset.
 */
export type ResetPasswordRequest = {
    token: string;
    password: string;
};

/**
 * Request body for POST /servers/{id}/rollback.
 */
export type RollbackRequest = {
    version: number;
};

/**
 * Paginated list of scan results for a server.
 */
export type ScanHistoryResponse = {
    items: Array<ScanResultResponse>;
    total: number;
    page: number;
    page_size: number;
    next_page?: (number | null);
};

/**
 * Response for GET /api/v1/servers/{id}/security/latest.
 */
export type ScanResultResponse = {
    id: string;
    server_id: string;
    scan_status: 'running' | 'completed' | 'failed';
    findings: Array<Finding>;
    critical_count: number;
    high_count: number;
    medium_count: number;
    info_count: number;
    scanned_at: string;
    scan_duration_ms: (number | null);
};

export type scan_status = 'running' | 'completed' | 'failed';

/**
 * Response when a security scan is initiated.
 */
export type ScanTriggerResponse = {
    scan_id: string;
    scan_status?: string;
    message?: string;
};

/**
 * JSON export of a server's security posture.
 */
export type SecurityReport = {
    server_id: string;
    server_name?: string;
    generated_at: string;
    scan?: (ScanResultResponse | null);
    acknowledgments?: Array<AcknowledgeResponse>;
    summary?: string;
};

/**
 * A version snapshot of a server's configuration.
 */
export type ServerVersionResponse = {
    id: string;
    version: number;
    change_note?: (string | null);
    changed_by?: (string | null);
    changed_by_email?: (string | null);
    created_at: string;
};

/**
 * Paginated list of version snapshots.
 */
export type ServerVersionsResponse = {
    items: Array<ServerVersionResponse>;
    total: number;
    skip?: number;
    limit?: number;
};

/**
 * Request body for POST /specs/fetch.
 */
export type SpecFetchRequest = {
    url: string;
    headers?: ({
    [key: string]: (string);
} | null);
};

/**
 * Response for GET /specs/{spec_id} — spec metadata.
 */
export type SpecSourceResponse = {
    id: string;
    user_id: string;
    source_type: string;
    source_url?: (string | null);
    r2_key?: (string | null);
    title?: (string | null);
    version?: (string | null);
    openapi_version?: (string | null);
    endpoint_count?: (number | null);
    spec_size_bytes?: (number | null);
    fetch_status?: string;
    fetch_error?: (string | null);
    created_at: string;
    updated_at?: (string | null);
};

/**
 * Response for GET /api/v1/specs/{spec_id}/tools.
 */
export type SpecToolListResponse = {
    spec_id: string;
    tools: Array<ToolDefinition>;
};

/**
 * Response for a successful spec upload/fetch.
 */
export type SpecUploadResponse = {
    spec_id: string;
    title: (string | null);
    version: (string | null);
    openapi_version: (string | null);
    endpoint_count: number;
    spec_size_bytes: number;
    tools?: Array<ToolDefinition>;
};

/**
 * POST /api/v1/billing/subscribe — subscribe to a plan.
 */
export type SubscribeRequest = {
    plan: 'pro' | 'team';
    billing_period?: 'monthly' | 'yearly';
    /**
     * Number of seats (team plan only)
     */
    seats?: number;
};

export type plan = 'pro' | 'team';

export type billing_period = 'monthly' | 'yearly';

/**
 * A user's current subscription.
 */
export type SubscriptionResponse = {
    id: string;
    plan: string;
    status: string;
    current_period_start?: (string | null);
    current_period_end?: (string | null);
    cancel_at_period_end?: boolean;
};

/**
 * POST /api/v1/team/accept — accept an invitation by token.
 */
export type TeamAcceptRequest = {
    token: string;
};

/**
 * POST /api/v1/team — create a new team.
 */
export type TeamCreateRequest = {
    name: string;
};

/**
 * A team invitation.
 *
 * The ``token`` field is only included in the creation response;
 * subsequent GET responses MUST exclude it.
 */
export type TeamInvitationResponse = {
    id: string;
    email: string;
    role: 'admin' | 'editor' | 'viewer';
    token?: (string | null);
    expires_at: string;
    accepted_at?: (string | null);
    created_at: string;
};

export type role = 'admin' | 'editor' | 'viewer';

/**
 * POST /api/v1/team/invite — invite a user by email.
 */
export type TeamInviteRequest = {
    email: string;
    role?: 'admin' | 'editor' | 'viewer';
};

/**
 * A single team member.
 */
export type TeamMemberResponse = {
    user_id: string;
    email: string;
    display_name?: (string | null);
    avatar_url?: (string | null);
    role: 'admin' | 'editor' | 'viewer';
    joined_at: string;
};

/**
 * PATCH /api/v1/team/members/{user_id} — change role.
 */
export type TeamMemberUpdateRequest = {
    role: 'admin' | 'editor' | 'viewer';
};

/**
 * Team representation.
 *
 * ``member_count`` and ``current_user_role`` are populated by the
 * service layer — they are not stored directly on the Team model.
 */
export type TeamResponse = {
    id: string;
    name: string;
    owner_id: string;
    plan: string;
    member_count?: number;
    current_user_role?: ('admin' | 'editor' | 'viewer' | null);
    created_at: string;
};

/**
 * PATCH /api/v1/team — update team name.
 */
export type TeamUpdateRequest = {
    name: string;
};

/**
 * POST /api/v1/servers/{id}/test-connection — result of a dry-run call.
 *
 * Unlike the credential test (which tests auth), this tests the full
 * MCP tool invocation pipeline from gateway through upstream.
 */
export type TestConnectionResponse = {
    success: boolean;
    response_time_ms: number;
    tools_count?: (number | null);
    error?: (string | null);
};

/**
 * POST /api/v1/servers/{id}/tools/accept — accept/reject AI suggestions.
 */
export type ToolAcceptRequest = {
    /**
     * Tool names whose AI enhancements to accept
     */
    accepted_tools: Array<(string)>;
    /**
     * Tool names whose AI enhancements to reject (keep original)
     */
    rejected_tools?: Array<(string)>;
    /**
     * Manual overrides keyed by tool name, value is a dict of fields to set
     */
    custom_edits?: {
        [key: string]: {
            [key: string]: unknown;
        };
    };
};

export type ToolDefinition = {
    [key: string]: unknown;
};

/**
 * Response for GET /api/v1/servers/{id}/tools.
 */
export type ToolListResponse = {
    server_id: string;
    tool_count: number;
    tools: Array<{
        [key: string]: unknown;
    }>;
};

/**
 * Request body for POST /specs/{spec_id}/select-tools.
 */
export type ToolSelectionRequest = {
    /**
     * Lowercase alphanumeric with hyphens, 3-50 chars
     */
    slug: string;
    name: string;
    base_url: string;
    description?: (string | null);
    auth_scheme?: string;
    auth_header_name?: (string | null);
    /**
     * Names of tools the user selected to include
     */
    selected_tool_names: Array<(string)>;
    customizations?: ({
    [key: string]: {
        [key: string]: unknown;
    };
} | null);
    transport_mode?: string;
};

/**
 * Request body for PATCH /api/v1/servers/{id}/tools/{tool_name}.
 *
 * All fields are optional. Only non-None values are applied.
 */
export type ToolUpdateRequest = {
    description?: (string | null);
    enabled?: (boolean | null);
    name?: (string | null);
};

/**
 * Public user profile response.
 */
export type UserResponse = {
    id: string;
    email: string;
    display_name?: (string | null);
    avatar_url?: (string | null);
    plan?: string;
    ai_enhancement_credits?: number;
    email_verified?: boolean;
    created_at: string;
    updated_at?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

/**
 * Request body for email verification.
 */
export type VerifyEmailRequest = {
    token: string;
};

export type AnalyticsOverviewApiV1ServersServerIdAnalyticsGetData = {
    serverId: string;
};

export type ToolBreakdownApiV1ServersServerIdAnalyticsToolsGetData = {
    serverId: string;
};

export type ErrorLogApiV1ServersServerIdAnalyticsErrorsGetData = {
    serverId: string;
};

export type ClientBreakdownApiV1ServersServerIdAnalyticsClientsGetData = {
    serverId: string;
};

export type TimeseriesApiV1ServersServerIdAnalyticsTimeseriesGetData = {
    serverId: string;
};

export type ExportCsvApiV1ServersServerIdAnalyticsExportCsvGetData = {
    serverId: string;
};

export type ListApiKeysApiV1ApiKeysGetData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    includeRevoked?: boolean;
};

export type ListApiKeysApiV1ApiKeysGetResponse = (ApiKeyListResponse);

export type CreateApiKeyApiV1ApiKeysPostData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    requestBody: ApiKeyCreateRequest;
};

export type CreateApiKeyApiV1ApiKeysPostResponse = (ApiKeyCreatedResponse);

export type RevokeApiKeyApiV1ApiKeysKeyIdDeleteData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    keyId: string;
};

export type RevokeApiKeyApiV1ApiKeysKeyIdDeleteResponse = (void);

export type RegisterApiV1AuthRegisterPostData = {
    requestBody: RegisterRequest;
};

export type RegisterApiV1AuthRegisterPostResponse = (AuthResponse);

export type LoginApiV1AuthLoginPostData = {
    requestBody: LoginRequest;
};

export type LoginApiV1AuthLoginPostResponse = (AuthResponse);

export type RefreshTokenApiV1AuthRefreshPostData = {
    refreshToken?: (string | null);
};

export type RefreshTokenApiV1AuthRefreshPostResponse = (AuthResponse);

export type LogoutApiV1AuthLogoutPostData = {
    accessToken?: (string | null);
    authorization?: (string | null);
};

export type LogoutApiV1AuthLogoutPostResponse = ({
    [key: string]: (string);
});

export type GetMeApiV1AuthMeGetData = {
    accessToken?: (string | null);
    authorization?: (string | null);
};

export type GetMeApiV1AuthMeGetResponse = (UserResponse);

export type ForgotPasswordApiV1AuthForgotPasswordPostData = {
    requestBody: ForgotPasswordRequest;
};

export type ForgotPasswordApiV1AuthForgotPasswordPostResponse = (MessageResponse);

export type ResetPasswordApiV1AuthResetPasswordPostData = {
    requestBody: ResetPasswordRequest;
};

export type ResetPasswordApiV1AuthResetPasswordPostResponse = (MessageResponse);

export type VerifyEmailApiV1AuthVerifyEmailPostData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    requestBody: VerifyEmailRequest;
};

export type VerifyEmailApiV1AuthVerifyEmailPostResponse = (UserResponse);

export type ResendVerificationApiV1AuthResendVerificationPostData = {
    accessToken?: (string | null);
    authorization?: (string | null);
};

export type ResendVerificationApiV1AuthResendVerificationPostResponse = (MessageResponse);

export type GithubOauthStartApiV1AuthGithubGetResponse = (unknown);

export type GithubOauthCallbackApiV1AuthGithubCallbackGetData = {
    code?: (string | null);
    state?: (string | null);
};

export type GithubOauthCallbackApiV1AuthGithubCallbackGetResponse = (unknown);

export type ListPlansApiV1BillingPlansGetResponse = (PlansResponse);

export type SubscribeApiV1BillingSubscribePostData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    requestBody: SubscribeRequest;
};

export type SubscribeApiV1BillingSubscribePostResponse = (CheckoutResponse);

export type CustomerPortalApiV1BillingPortalPostData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    requestBody: PortalRequest;
};

export type CustomerPortalApiV1BillingPortalPostResponse = (PortalResponse);

export type StripeWebhookApiV1BillingWebhookPostResponse = ({
    [key: string]: unknown;
});

export type GetSubscriptionApiV1BillingSubscriptionGetData = {
    accessToken?: (string | null);
    authorization?: (string | null);
};

export type GetSubscriptionApiV1BillingSubscriptionGetResponse = (SubscriptionResponse);

export type ListInvoicesApiV1BillingInvoicesGetData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    limit?: number;
    skip?: number;
};

export type ListInvoicesApiV1BillingInvoicesGetResponse = (InvoicesListResponse);

export type StartBuildApiV1ServersServerIdBuildPostData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    serverId: string;
};

export type StartBuildApiV1ServersServerIdBuildPostResponse = (AIEnhancementResponse);

export type BuildStatusSseApiV1ServersServerIdBuildStatusGetData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    serverId: string;
};

export type BuildStatusSseApiV1ServersServerIdBuildStatusGetResponse = (unknown);

export type AcceptAiEnhancementsApiV1ServersServerIdToolsAcceptPostData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    requestBody: ToolAcceptRequest;
    serverId: string;
};

export type AcceptAiEnhancementsApiV1ServersServerIdToolsAcceptPostResponse = ({
    [key: string]: unknown;
});

export type DeployServerApiV1ServersServerIdDeployPostData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    serverId: string;
};

export type DeployServerApiV1ServersServerIdDeployPostResponse = ({
    [key: string]: unknown;
});

export type ListCredentialsApiV1ServersServerIdCredentialsGetData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    serverId: string;
};

export type ListCredentialsApiV1ServersServerIdCredentialsGetResponse = (CredentialListResponse);

export type AddCredentialApiV1ServersServerIdCredentialsPostData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    requestBody: CredentialCreateRequest;
    serverId: string;
};

export type AddCredentialApiV1ServersServerIdCredentialsPostResponse = (CredentialResponse);

export type TestCredentialApiV1ServersServerIdCredentialsTestPostData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    requestBody: CredentialTestRequest;
    serverId: string;
};

export type TestCredentialApiV1ServersServerIdCredentialsTestPostResponse = (CredentialTestResponse);

export type DeleteCredentialApiV1ServersServerIdCredentialsEnvVarNameDeleteData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    envVarName: string;
    serverId: string;
};

export type DeleteCredentialApiV1ServersServerIdCredentialsEnvVarNameDeleteResponse = (void);

export type McpServerHealthMcpV1SlugHealthGetData = {
    slug: string;
};

export type McpServerHealthMcpV1SlugHealthGetResponse = ({
    [key: string]: (string);
});

export type McpSseEndpointMcpV1SlugSseGetData = {
    slug: string;
};

export type McpSseEndpointMcpV1SlugSseGetResponse = (unknown);

export type McpMessageEndpointMcpV1SlugMessagePostData = {
    sessionId?: (string | null);
    slug: string;
};

export type McpMessageEndpointMcpV1SlugMessagePostResponse = (unknown);

export type McpHttpGetEndpointMcpV1SlugGetData = {
    slug: string;
};

export type McpHttpGetEndpointMcpV1SlugGetResponse = (unknown);

export type McpHttpEndpointMcpV1SlugPostData = {
    slug: string;
};

export type McpHttpEndpointMcpV1SlugPostResponse = (unknown);

export type HealthCheckHealthGetResponse = (HealthResponse);

export type ListVersionsApiV1ServersServerIdVersionsGetData = {
    serverId: string;
};

export type RollbackServerApiV1ServersServerIdRollbackPostData = {
    serverId: string;
};

export type ConnectPanelApiV1ServersServerIdConnectGetData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    serverId: string;
};

export type ConnectPanelApiV1ServersServerIdConnectGetResponse = (ConnectPanelResponse);

export type TestConnectionApiV1ServersServerIdConnectTestPostData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    serverId: string;
};

export type TestConnectionApiV1ServersServerIdConnectTestPostResponse = (TestConnectionResponse);

export type PauseServerApiV1ServersServerIdPausePostData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    serverId: string;
};

export type PauseServerApiV1ServersServerIdPausePostResponse = (PauseResponse);

export type ResumeServerApiV1ServersServerIdResumePostData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    serverId: string;
};

export type ResumeServerApiV1ServersServerIdResumePostResponse = (PauseResponse);

export type TriggerScanApiV1ServersServerIdSecurityScanPostData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    serverId: string;
};

export type TriggerScanApiV1ServersServerIdSecurityScanPostResponse = (ScanTriggerResponse);

export type GetLatestScanApiV1ServersServerIdSecurityLatestGetData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    serverId: string;
};

export type GetLatestScanApiV1ServersServerIdSecurityLatestGetResponse = ((ScanResultResponse | null));

export type ListScansApiV1ServersServerIdSecurityScansGetData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    page?: number;
    pageSize?: number;
    serverId: string;
};

export type ListScansApiV1ServersServerIdSecurityScansGetResponse = (ScanHistoryResponse);

export type AcknowledgeFindingApiV1ServersServerIdSecurityFindingIdAcknowledgePostData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    findingId: string;
    requestBody: AcknowledgeRequest;
    serverId: string;
};

export type AcknowledgeFindingApiV1ServersServerIdSecurityFindingIdAcknowledgePostResponse = (AcknowledgeResponse);

export type RemoveAcknowledgmentApiV1ServersServerIdSecurityFindingIdAcknowledgeDeleteData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    findingId: string;
    serverId: string;
};

export type RemoveAcknowledgmentApiV1ServersServerIdSecurityFindingIdAcknowledgeDeleteResponse = (void);

export type ExportReportApiV1ServersServerIdSecurityReportJsonGetData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    serverId: string;
};

export type ExportReportApiV1ServersServerIdSecurityReportJsonGetResponse = (SecurityReport);

export type ListAcknowledgmentsApiV1ServersServerIdSecurityAcknowledgmentsGetData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    serverId: string;
};

export type ListAcknowledgmentsApiV1ServersServerIdSecurityAcknowledgmentsGetResponse = ({
    [key: string]: unknown;
});

export type ApiHealthApiV1ServersHealthGetResponse = (APIHealthResponse);

export type ListServersApiV1ServersGetData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    limit?: number;
    skip?: number;
};

export type ListServersApiV1ServersGetResponse = (Array<MCPServerResponse>);

export type CreateServerApiV1ServersPostData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    requestBody: MCPServerCreate;
};

export type CreateServerApiV1ServersPostResponse = (MCPServerResponse);

export type GetServerApiV1ServersServerIdGetData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    serverId: string;
};

export type GetServerApiV1ServersServerIdGetResponse = (MCPServerResponse);

export type UpdateServerApiV1ServersServerIdPatchData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    requestBody: MCPServerUpdate;
    serverId: string;
};

export type UpdateServerApiV1ServersServerIdPatchResponse = (MCPServerResponse);

export type DeleteServerApiV1ServersServerIdDeleteData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    serverId: string;
};

export type DeleteServerApiV1ServersServerIdDeleteResponse = (void);

export type DuplicateServerApiV1ServersServerIdDuplicatePostData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    requestBody: DuplicateServerRequest;
    serverId: string;
};

export type DuplicateServerApiV1ServersServerIdDuplicatePostResponse = (MCPServerResponse);

export type FetchSpecApiV1SpecsFetchPostData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    requestBody: SpecFetchRequest;
};

export type FetchSpecApiV1SpecsFetchPostResponse = (SpecUploadResponse);

export type UploadSpecApiV1SpecsUploadPostData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    formData: Body_upload_spec_api_v1_specs_upload_post;
};

export type UploadSpecApiV1SpecsUploadPostResponse = (SpecUploadResponse);

export type GetSpecToolsApiV1SpecsSpecIdToolsGetData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    specId: string;
};

export type GetSpecToolsApiV1SpecsSpecIdToolsGetResponse = (SpecToolListResponse);

export type SelectToolsApiV1SpecsSpecIdSelectToolsPostData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    requestBody: ToolSelectionRequest;
    specId: string;
};

export type SelectToolsApiV1SpecsSpecIdSelectToolsPostResponse = (MCPServerResponse);

export type GetSpecApiV1SpecsSpecIdGetData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    specId: string;
};

export type GetSpecApiV1SpecsSpecIdGetResponse = (SpecSourceResponse);

export type DeleteSpecApiV1SpecsSpecIdDeleteData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    specId: string;
};

export type DeleteSpecApiV1SpecsSpecIdDeleteResponse = (void);

export type GetTeamApiV1TeamGetData = {
    accessToken?: (string | null);
    authorization?: (string | null);
};

export type GetTeamApiV1TeamGetResponse = (TeamResponse);

export type CreateTeamApiV1TeamPostData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    requestBody: TeamCreateRequest;
};

export type CreateTeamApiV1TeamPostResponse = (TeamResponse);

export type UpdateTeamApiV1TeamPatchData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    requestBody: TeamUpdateRequest;
};

export type UpdateTeamApiV1TeamPatchResponse = (TeamResponse);

export type InviteMemberApiV1TeamInvitePostData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    requestBody: TeamInviteRequest;
};

export type InviteMemberApiV1TeamInvitePostResponse = (TeamInvitationResponse);

export type AcceptInvitationApiV1TeamAcceptPostData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    requestBody: TeamAcceptRequest;
};

export type AcceptInvitationApiV1TeamAcceptPostResponse = (TeamMemberResponse);

export type ListMembersApiV1TeamMembersGetData = {
    accessToken?: (string | null);
    authorization?: (string | null);
};

export type ListMembersApiV1TeamMembersGetResponse = (Array<TeamMemberResponse>);

export type UpdateMemberApiV1TeamMembersUserIdPatchData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    requestBody: TeamMemberUpdateRequest;
    userId: string;
};

export type UpdateMemberApiV1TeamMembersUserIdPatchResponse = (TeamMemberResponse);

export type RemoveMemberApiV1TeamMembersUserIdDeleteData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    userId: string;
};

export type RemoveMemberApiV1TeamMembersUserIdDeleteResponse = (void);

export type AuditLogApiV1TeamAuditLogGetData = {
    accessToken?: (string | null);
    action?: (string | null);
    authorization?: (string | null);
    limit?: number;
    skip?: number;
};

export type AuditLogApiV1TeamAuditLogGetResponse = (PaginatedAuditLogResponse);

export type ListToolsApiV1ServersServerIdToolsGetData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    serverId: string;
};

export type ListToolsApiV1ServersServerIdToolsGetResponse = (ToolListResponse);

export type UpdateToolApiV1ServersServerIdToolsToolNamePatchData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    requestBody: ToolUpdateRequest;
    serverId: string;
    toolName: string;
};

export type UpdateToolApiV1ServersServerIdToolsToolNamePatchResponse = ({
    [key: string]: unknown;
});

export type EnhanceToolsApiV1ServersServerIdToolsEnhancePostData = {
    accessToken?: (string | null);
    authorization?: (string | null);
    requestBody: AIEnhancementRequest;
    serverId: string;
};

export type EnhanceToolsApiV1ServersServerIdToolsEnhancePostResponse = (AIEnhancementResponse);